base_cfg: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/2025_09_03_scaling/base.yaml
output_path: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/2025_09_03_scaling/OUT_marine_3.yaml

dataset_cfgs:
  - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_landsat_vessels/finetune_detector_cosinelr.yaml
  - - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_satlas_wind_turbine_128/basecfg_cosinelr.yaml
    - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_satlas_wind_turbine_128/basecfg_helios_mm.yaml
  - - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_sentinel1_vessels_128/basecfg_cosinelr.yaml
    - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_sentinel1_vessels_128/basecfg_helios.yaml
  - - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_sentinel2_vessels_128/basecfg_cosinelr.yaml
    - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_sentinel2_vessels_128/basecfg_helios.yaml
 
substitutions:
  patch_size: 8
  encoder_embedding_size: 768
  helios_checkpoint_path: /weka/dfive-default/helios/checkpoints/favyen/v0.2_base_latent_mim_128_alldata_random_fixed_modality_0.5/step320000

global_overrides:
  model:
    class_path: rslearn.train.lightning_module.RslearnLightningModule
    init_args:
      model:
        init_args:
          trunk:
            class_path: rslearn.models.trunk.DecoderTrunk
            init_args:
              task_embedding:
                class_path: rslearn.models.task_embedding.TaskChannelEmbedding
                init_args:
                  encoder_embedding_size: 768
                  add_spatial_embed: true
              layers:
                - class_path: rslp.helios.moe.MoETransformer
                  init_args:
                    dim: 768
                    n_layers: 1
                    n_heads: 12
                    num_experts: 4
                    num_slots: 4
  trainer:
    accumulate_grad_batches: 4
    callbacks+:
      - class_path: rslearn.train.callbacks.freeze_unfreeze.MultiStageFineTuning
        init_args:
          stages:
            - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
              init_args:
                at_epoch: 0
                freeze_selectors: ["encoder"]
                unfreeze_selectors: ["head", "moe"]
            - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
              init_args:
                at_epoch: 20
                freeze_selectors: []
                unfreeze_selectors: ["encoder", "head", "moe"]
                unfreeze_lr_factor: 10

merge_options:
  merge_heads: true
  merge_task_labels: true
  same_label_groups:
    - [detect_sentinel1_vessels, detect_sentinel2_vessels, vessel_detection]
