data:
  class_path: rslearn.train.data_module.MultiDatasetDataModule
  init_args:
    batch_sizes:
      crop_type_classification: 32
    data_modules:
      crop_type_classification:
        class_path: rslearn.train.data_module.RslearnDataModule
        init_args:
          batch_size: 32
          default_config:
            transforms:
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel2_l2a
                selections:
                  sentinel2_0: []
                  sentinel2_1: []
                  sentinel2_10: []
                  sentinel2_11: []
                  sentinel2_2: []
                  sentinel2_3: []
                  sentinel2_4: []
                  sentinel2_5: []
                  sentinel2_6: []
                  sentinel2_7: []
                  sentinel2_8: []
                  sentinel2_9: []
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel1
                selections:
                  sentinel1_0: []
                  sentinel1_1: []
                  sentinel1_10: []
                  sentinel1_11: []
                  sentinel1_2: []
                  sentinel1_3: []
                  sentinel1_4: []
                  sentinel1_5: []
                  sentinel1_6: []
                  sentinel1_7: []
                  sentinel1_8: []
                  sentinel1_9: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  sentinel1:
                  - vv
                  - vh
                  sentinel2_l2a:
                  - B02
                  - B03
                  - B04
                  - B08
                  - B05
                  - B06
                  - B07
                  - B8A
                  - B11
                  - B12
                  - B01
                  - B09
                config_fname: /opt/helios/data/norm_configs/computed.json
            - class_path: rslearn.train.transforms.pad.Pad
              init_args:
                image_selectors:
                - sentinel2_l2a
                - sentinel1
                mode: center
                size: 8
          inputs:
            label:
              data_type: vector
              is_target: true
              layers:
              - label
            sentinel1_0:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending
              passthrough: true
            sentinel1_1:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.1
              passthrough: true
            sentinel1_10:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.10
              passthrough: true
            sentinel1_11:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.11
              passthrough: true
            sentinel1_2:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.2
              passthrough: true
            sentinel1_3:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.3
              passthrough: true
            sentinel1_4:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.4
              passthrough: true
            sentinel1_5:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.5
              passthrough: true
            sentinel1_6:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.6
              passthrough: true
            sentinel1_7:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.7
              passthrough: true
            sentinel1_8:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.8
              passthrough: true
            sentinel1_9:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1_ascending.9
              passthrough: true
            sentinel2_0:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2
              passthrough: true
            sentinel2_1:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.1
              passthrough: true
            sentinel2_10:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.10
              passthrough: true
            sentinel2_11:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.11
              passthrough: true
            sentinel2_2:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.2
              passthrough: true
            sentinel2_3:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.3
              passthrough: true
            sentinel2_4:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.4
              passthrough: true
            sentinel2_5:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.5
              passthrough: true
            sentinel2_6:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.6
              passthrough: true
            sentinel2_7:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.7
              passthrough: true
            sentinel2_8:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.8
              passthrough: true
            sentinel2_9:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.9
              passthrough: true
          num_workers: 32
          path: /weka/dfive-default/rslearn-eai/datasets/crop/kenya_nandi/20250625
          task:
            class_path: rslearn.train.tasks.multi_task.MultiTask
            init_args:
              input_mapping:
                crop_type_classification:
                  label: targets
              tasks:
                crop_type_classification:
                  class_path: rslearn.train.tasks.classification.ClassificationTask
                  init_args:
                    classes:
                    - Coffee
                    - Trees
                    - Grassland
                    - Maize
                    - Sugarcane
                    - Tea
                    - Water
                    - Built-up
                    enable_f1_metric: true
                    metric_kwargs:
                      average: micro
                    property_name: category
          test_config:
            groups:
            - groundtruth_polygon_split_window_32
            - worldcover_window_32
            tags:
              split: val
          train_config:
            groups:
            - groundtruth_polygon_split_window_32
            - worldcover_window_32
            tags:
              split: train
          val_config:
            groups:
            - groundtruth_polygon_split_window_32
            - worldcover_window_32
            tags:
              split: val
    num_workers: 16
    refill_batches: true
    sample_mode: random_cycle
model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    lr: 0.0002
    model:
      class_path: rslearn.models.multitask.MultiTaskMergedModel
      init_args:
        decoder_to_target:
          ClassificationHead:
          - crop_type_classification
        decoders:
          ClassificationHead:
          - class_path: rslearn.models.pooling_decoder.PoolingDecoder
            init_args:
              in_channels: 768
              out_channels: 8
          - class_path: rslearn.train.tasks.classification.ClassificationHead
        encoder:
        - class_path: rslp.helios.model.TaskConditionedHelios
          init_args:
            checkpoint_path: '{CHECKPOINT_PATH}'
            forward_kwargs:
              patch_size: 8
            model_overrides:
              encoder_config:
                task_lora_kwargs:
                  gen_hidden: 64
                  task_lora_indices:
                  - 0
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  - 6
                  - 7
                  - 8
                  - 9
                  - 10
                  - 11
                  use_task_lora: true
            selector:
            - encoder
            task_embed_opts:
              path: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/data/task_embeds___Qwen3-Embedding-8B__256d__anchor__instruct__from_yaml.pt
              type: precomputed
        lazy_decode: true
        task_label_offsets:
          crop_type_classification:
            num_outputs: 8
            offset: 0
            outputs_key: class
    scheduler:
      class_path: rslearn.train.scheduler.CosineAnnealingScheduler
      init_args:
        T_max: 50
        eta_min: 0
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        input_mapping:
          crop_type_classification:
            label: targets
        tasks:
          crop_type_classification:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              classes:
              - Coffee
              - Trees
              - Grassland
              - Maize
              - Sugarcane
              - Tea
              - Water
              - Built-up
              enable_f1_metric: true
              metric_kwargs:
                average: micro
              property_name: category
rslp_experiment: placeholder
rslp_project: placeholder
trainer:
  accumulate_grad_batches: 2
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      every_n_epochs: 10
      mode: min
      monitor: val_loss
      save_last: true
      save_top_k: 1
  - class_path: rslearn.train.callbacks.freeze_unfreeze.MultiStageFineTuning
    init_args:
      stages:
      - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
        init_args:
          at_epoch: 0
          freeze_selectors:
          - encoder
          unfreeze_selectors:
          - head
      - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
        init_args:
          at_epoch: 20
          freeze_selectors:
          - encoder
          unfreeze_selectors:
          - head
          - lora
      - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
        init_args:
          at_epoch: 50
          freeze_selectors: []
          unfreeze_lr_factor: 10
          unfreeze_selectors:
          - encoder
          - head
          - lora
  - class_path: rslearn.train.callbacks.adapters.ActivateLayers
    init_args:
      selectors:
      - at_epoch: 20
        name: lora
  max_epochs: 500
