# lightning.pytorch==2.4.0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: rslearn-landsat-recheck
      name: phase123_20240919_01_copy
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
      log_weight_decay: false
  - class_path: rslearn.train.prediction_writer.RslearnWriter
    init_args:
      path: gcs://rslearn-eai/datasets/landsat_vessel_detection/classifier/dataset_20240905/
      output_layer: output
      path_options: {}
      selector:
      - class
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      save_last: true
      save_top_k: 1
      monitor: val_loss
      dirpath: gs://rslearn-eai/projects/rslearn-landsat-recheck/phase123_20240919_01_copy/checkpoints/
  - class_path: rslp.lightning_cli.SaveWandbRunIdCallback
    init_args:
      project_id: rslearn-landsat-recheck
      experiment_id: phase123_20240919_01_copy
  fast_dev_run: false
  max_epochs: 64
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
wandb_run_id: ''
wandb_resume: false
rslp_project: rslearn-landsat-recheck
rslp_experiment: phase123_20240919_01_copy
autoresume: true
return_predictions: null
ckpt_path: gs://rslearn-eai/projects/rslearn-landsat-recheck/phase123_20240919_01_copy/checkpoints/last.ckpt
model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
        - class_path: rslearn.models.swin.Swin
          init_args:
            arch: swin_v2_b
            pretrained: true
            input_channels: 7
            output_layers:
            - 1
            - 3
            - 5
            - 7
            num_outputs: 1000
        decoders:
          class:
          - class_path: rslearn.models.pooling_decoder.PoolingDecoder
            init_args:
              in_channels: 1024
              out_channels: 2
              num_conv_layers: 0
              num_fc_layers: 0
              conv_channels: 128
              fc_channels: 512
          - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.0001
    plateau: false
    plateau_factor: 0.1
    plateau_patience: 10
    plateau_min_lr: 0.0
    plateau_cooldown: 0
    visualize_dir: null
    restore_config:
      class_path: rslearn.train.lightning_module.RestoreConfig
      init_args:
        restore_path: gcs://rslearn-eai/datasets/landsat_vessel_detection/artifacts/2024-03-13-landsat-vessels/vessel02_satlas_freeze_crop512_nosatlas_b8first2/best.pth
        restore_path_options: {}
        selector: []
        ignore_prefixes: []
        remap_prefixes:
        - - backbone.backbone.
          - encoder.0.model.
    print_parameters: false
    print_model: false
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    inputs:
      image:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - landsat
          bands:
          - B8
          - B2
          - B3
          - B4
          - B5
          - B6
          - B7
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      label:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: vector
          layers:
          - label
          bands: null
          required: true
          passthrough: false
          is_target: true
          dtype: FLOAT32
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              property_name: label
              classes:
              - correct
              - incorrect
              filters: null
              read_class_id: false
              allow_invalid: true
              skip_unknown_categories: true
              prob_property: prob
              metric_kwargs: {}
              image_bands:
              - 0
              - 1
              - 2
              remap_values: null
        input_mapping:
          class:
            label: targets
    path: gcs://rslearn-eai/datasets/landsat_vessel_detection/classifier/dataset_20240905/
    path_options: {}
    batch_size: 32
    num_workers: 32
    default_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - selected
        - phase2a_completed
        - phase3a_selected
        names: null
        tags: null
        num_samples: null
        transforms:
        - class_path: rslearn.train.transforms.normalize.Normalize
          init_args:
            mean: 0.0
            std: 255.0
            valid_range: null
            selectors:
            - image
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 32
            mode: center
            image_selectors:
            - image
            box_selectors: []
        - class_path: rslearn.train.transforms.flip.Flip
          init_args:
            horizontal: true
            vertical: true
            image_selectors:
            - image
            box_selectors: []
        sampler: null
        patch_size: null
        load_all_patches: null
        skip_targets: null
    train_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups: null
        names: null
        tags:
          split: train
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        load_all_patches: null
        skip_targets: null
    val_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - phase2a_completed
        names: null
        tags:
          split: val
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        load_all_patches: null
        skip_targets: null
    test_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - phase2a_completed
        names: null
        tags:
          split: val
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        load_all_patches: null
        skip_targets: null
    predict_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - phase2a_completed
        names: null
        tags:
          split: val
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        load_all_patches: null
        skip_targets: null
