# The intention for this Dockerfile is to have dev version of rslearn in a subfolder of
# the rslearn_projects repository, so that users can modify rslearn and use the Docker
# image (e.g. on Beaker) with those changes before merging them into master.

# To use this image, setup rslearn/ under rslearn_projects like this:
# rslearn_projects/
#     Dockerfile
#     ...
#     rslearn/
#         ...

FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime@sha256:58a28ab734f23561aa146fbaf777fb319a953ca1e188832863ed57d510c9f197

RUN apt update
RUN apt install -y libpq-dev ffmpeg libsm6 libxext6 git
# COPY instead of git clone.
COPY rslearn/ /opt/rslearn_projects/rslearn/
RUN pip install --no-cache-dir --upgrade -r /opt/rslearn_projects/rslearn/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /opt/rslearn_projects/rslearn/extra_requirements.txt
COPY requirements.txt /opt/rslearn_projects/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /opt/rslearn_projects/requirements.txt

ENV PYTHONPATH="${PYTHONPATH}:/opt/rslearn_projects/rslearn:."

COPY /. /opt/rslearn_projects/
WORKDIR /opt/rslearn_projects
