model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslp.helios.model.Helios
            init_args:
              checkpoint_path: ${EXTRA_FILES_PATH}/yawenzzzz/latent_mim_cross_random_per_modality_patchdisc_add_contrastive_0.1_1/step400000
              random_initialization: true
              selector: ["encoder"]
              forward_kwargs:
                patch_size: 1
        decoders:
          class:
            - class_path: rslp.nandi.train.SegmentationPoolingDecoder
              init_args:
                in_channels: 768
                out_channels: 11
            - class_path: rslearn.train.tasks.segmentation.SegmentationHead
    lr: 0.0001
    plateau: true
    plateau_factor: 0.2
    plateau_patience: 2
    plateau_min_lr: 0
    plateau_cooldown: 10
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: ${DATASET_PATH}
    inputs:
      sentinel2_l2a:
        data_type: "raster"
        layers: ["sentinel2"]
        bands: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
        passthrough: true
        dtype: FLOAT32
        load_all_item_groups: true
        load_all_layers: true
      label:
        data_type: "raster"
        layers: ["label_raster"]
        bands: ["label"]
        is_target: true
        dtype: INT32
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslearn.train.tasks.segmentation.SegmentationTask
            init_args:
              num_classes: 11
              zero_is_invalid: true
              metric_kwargs:
                average: "micro"
              other_metrics:
                coffee_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 1
                coffee_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 1
                trees_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 2
                trees_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 2
                grassland_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 3
                grassland_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 3
                maize_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 4
                maize_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 4
                sugarcane_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 5
                sugarcane_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 5
                tea_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 6
                tea_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 6
                vegetables_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 7
                vegetables_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 7
                legumes_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 8
                legumes_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 8
                water_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 9
                water_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 9
                builtup_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 10
                builtup_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 11
                        average: null
                    class_idx: 10
        input_mapping:
          class:
            label: "targets"
    batch_size: 32
    num_workers: ${NUM_WORKERS}
    default_config:
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 4
            mode: "center"
            image_selectors: ["sentinel2_l2a", "target/crop_type_classification/classes", "target/crop_type_classification/valid"]
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
    train_config:
      groups: ["groundtruth_polygon_split_window_32", "worldcover_window_32"]
      tags:
        split: "train"
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 4
            mode: "center"
            image_selectors: ["sentinel2_l2a", "target/crop_type_classification/classes", "target/crop_type_classification/valid"]
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
    val_config:
      groups: ["groundtruth_polygon_split_window_32", "worldcover_window_32"]
      tags:
        split: "val"
    test_config:
      groups: ["groundtruth_polygon_split_window_32", "worldcover_window_32"]
      tags:
        split: "val"
    predict_config:
      groups: ["nandi_county"]
      load_all_patches: true
      skip_targets: true
      overlap_ratio: 0.75
      patch_size: 4
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 4
            mode: "center"
            image_selectors: ["sentinel2_l2a"]
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
trainer:
  max_epochs: 100
  default_root_dir: ${TRAINER_DATA_PATH}
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: ${WANDB_PROJECT}
      name: ${WANDB_NAME}
      entity: ${WANDB_ENTITY}
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_loss
        mode: min
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0]
        unfreeze_at_epoch: 2
    - class_path: rslearn.train.prediction_writer.RslearnWriter
      init_args:
        path: placeholder
        output_layer: ${PREDICTION_OUTPUT_LAYER}
        selector: ["class"]
        merger:
          class_path: rslearn.train.prediction_writer.RasterMerger
          init_args:
            padding: 2
