model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslp.helios.model.Helios
            init_args:
              checkpoint_path: "{CHECKPOINT_PATH}"
              selector: ["encoder"]
              forward_kwargs:
                patch_size: {PATCH_SIZE}
        decoders:
          detect_sentinel1_vessels:
            - class_path: rslearn.models.faster_rcnn.FasterRCNN
              init_args:
                downsample_factors: [{PATCH_SIZE}]
                num_channels: {ENCODER_EMBEDDING_SIZE}
                num_classes: 2
                anchor_sizes: [[32]]
data:
  init_args:
    inputs:
      image:
        data_type: "raster"
        layers: ["sentinel1"]
        bands: ["vv", "vh"]
        passthrough: true
        dtype: FLOAT32
      mask:
        data_type: "raster"
        layers: ["mask"]
        bands: ["mask"]
        passthrough: true
        dtype: INT32
        is_target: true
      targets:
        data_type: "vector"
        layers: ["label"]
        is_target: true
    default_config:
      transforms:
        - class_path: rslp.transforms.mask.Mask
        - class_path: rslearn.train.transforms.concatenate.Concatenate
          init_args:
            selections:
              image: []
            output_selector: sentinel1
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            config_fname: "/opt/helios/data/norm_configs/computed.json"
            band_names:
              sentinel1: ["vv", "vh"]
    train_config:
      transforms:
        - class_path: rslp.transforms.mask.Mask
        - class_path: rslearn.train.transforms.concatenate.Concatenate
          init_args:
            selections:
              image: []
            output_selector: sentinel1
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            config_fname: "/opt/helios/data/norm_configs/computed.json"
            band_names:
              sentinel1: ["vv", "vh"]
        - class_path: rslearn.train.transforms.flip.Flip
          init_args:
            image_selectors: ["image", "sentinel1"]
            box_selectors: ["target/detect_sentinel1_vessels"]
