model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        decoders:
          detect_sentinel2_vessels:
            - class_path: rslearn.models.faster_rcnn.FasterRCNN
              init_args:
                downsample_factors: [4, 8, 16, 32]
                num_channels: 128
                num_classes: 2
                anchor_sizes: [[32], [64], [128], [256]]
    lr: 0.0001
    scheduler:
      class_path: rslearn.train.scheduler.CosineAnnealingScheduler
      init_args:
        T_max: 100
        eta_min: 0
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: /weka/dfive-default/rslearn-eai/datasets/sentinel2_vessels/dataset_v1/20250213/
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          detect_sentinel2_vessels:
            class_path: rslearn.train.tasks.detection.DetectionTask
            init_args:
              property_name: "category"
              classes: ["unknown", "vessel"]
              box_size: 15
              remap_values: [[0, 1], [0, 255]]
              exclude_by_center: true
              enable_map_metric: true
              enable_f1_metric: true
              f1_metric_thresholds: [[0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]]
              f1_metric_kwargs:
                cmp_mode: "distance"
                cmp_threshold: 15
                flatten_classes: true
        input_mapping:
          detect_sentinel2_vessels:
            targets: "targets"
    batch_size: 8
    num_workers: 16
    train_config:
      patch_size: 128
      groups: ["sargassum_train", "split2", "split3", "split4", "split5", "split6", "train", "train-bg", "train2", "train3"]
      sampler:
        class_path: rslearn.train.dataset.RandomSamplerFactory
        init_args:
          replacement: true
          num_samples: 131072
    val_config:
      patch_size: 128
      load_all_patches: true
      groups: ["sargassum_val", "split1", "split7"]
    test_config:
      patch_size: 128
      load_all_patches: true
      groups: ["sargassum_val", "split1", "split7"]
trainer:
  max_epochs: 500
  limit_val_batches: 256
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_detect_sentinel2_vessels/mAP
        mode: max
rslp_project: placeholder
rslp_experiment: placeholder
