model:
  class_path: rslp.forest_loss_driver.train.ForestLossLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        # We use SimpleTimeSeries not for time series but just to concatenate the
        # feature maps for pre-forest-loss and post-forest-loss.
        encoder:
          - class_path: rslearn.models.simple_time_series.SimpleTimeSeries
            init_args:
              encoder:
                class_path: rslp.helios.model.Helios
                init_args:
                  checkpoint_path: "/weka/dfive-default/helios/checkpoints/henryh/base_v6.1_add_chm_cdl_worldcereal/step500000"
                  selector: ["encoder"]
                  forward_kwargs:
                    patch_size: 4
                  patch_size: 4
                  embedding_size: 768
              image_channels: 48
              image_key: "sentinel2_l2a"
              groups: [[0], [1]]
        decoders:
          class:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 1536
                out_channels: 10
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.0001
    plateau: true
    plateau_factor: 0.2
    plateau_patience: 2
    plateau_min_lr: 0
    plateau_cooldown: 10
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: gs://rslearn-eai/datasets/forest_loss_driver/dataset_v1/20250605/
    inputs:
      sentinel2_l2a:
        data_type: "raster"
        layers: ["pre_sentinel2", "pre_sentinel2.1", "pre_sentinel2.2", "pre_sentinel2.3", "post_sentinel2", "post_sentinel2.1", "post_sentinel2.2", "post_sentinel2.3"]
        bands: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
        passthrough: true
        load_all_layers: true
      label:
        data_type: "vector"
        layers: ["label"]
        is_target: true
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslp.forest_loss_driver.train.ForestLossTask
            init_args:
              property_name: "new_label"
              classes: ["agriculture", "mining", "airstrip", "road", "logging", "burned", "landslide", "hurricane", "river", "none"]
              allow_invalid: true
              metric_kwargs:
                average: "micro"
              prob_property: "probs"
        input_mapping:
          class:
            label: "targets"
    batch_size: 8
    num_workers: 64
    default_config:
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            mode: "center"
            size: 64
            image_selectors:
              - sentinel2_l2a
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
        - class_path: rslearn.train.transforms.flip.Flip
          init_args:
            image_selectors:
              - sentinel2_l2a
        # To support visualization via image key.
        - class_path: rslearn.train.transforms.concatenate.Concatenate
          init_args:
            selections:
              sentinel2_l2a: [2, 1, 0]
            output_selector: image
      groups: ["peru_interesting", "peru3", "peru3_flagged_in_peru", "nadia2", "nadia3", "brazil_interesting"]
    train_config:
      tags:
        split: train
    val_config:
      tags:
        split: val
    test_config:
      tags:
        split: val
    predict_config:
      groups: ["default"]
      skip_targets: true
trainer:
  max_epochs: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0, "encoder", "model"]
        unfreeze_at_epoch: 5
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_class/accuracy
        mode: max
    - class_path: rslearn.train.prediction_writer.RslearnWriter
      init_args:
        path: placeholder
        output_layer: output
        selector: ["class"]
rslp_project: 2025_06_12_forest_loss_helios
rslp_experiment: 20250612_forest_loss_driver_helios_finetune_20250930
