detect_sentinel1_vessels:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
detect_sentinel2_vessels:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
detect_satlas_wind_turbine:
  num_outputs: 3
  num_outputs_key: num_classes
  outputs_key: labels
detect_satlas_marine_infra:
  num_outputs: 3
  num_outputs_key: num_classes
  outputs_key: labels
segment_satlas_solar_farm:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: classes
vessel_classification:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: class
vessel_detection:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
cropland_classification:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: class
segment:
  num_outputs: 20
  num_outputs_key: out_channels
  outputs_key: classes
crop_type_classification:
  num_outputs: 8
  num_outputs_key: out_channels
  outputs_key: class