detect_sentinel1_vessels:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
  task_type: detect
detect_sentinel2_vessels:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
  task_type: detect
detect_satlas_wind_turbine:
  num_outputs: 3
  num_outputs_key: num_classes
  outputs_key: labels
  task_type: detect
detect_satlas_marine_infra:
  num_outputs: 3
  num_outputs_key: num_classes
  outputs_key: labels
  task_type: detect
segment_satlas_solar_farm:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: classes
  task_type: segment
vessel_classification:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: class
  task_type: classify
vessel_detection:
  num_outputs: 2
  num_outputs_key: num_classes
  outputs_key: labels
  task_type: detect
cropland_classification:
  num_outputs: 2
  num_outputs_key: out_channels
  outputs_key: class
  task_type: classify
segment:
  num_outputs: 20
  num_outputs_key: out_channels
  outputs_key: classes
  task_type: segment
crop_type_classification:
  num_outputs: 8
  num_outputs_key: out_channels
  outputs_key: class
  task_type: classify