"""Copy test and test_hard windows from the old Canada Fire Sat dataset.

Copies only the files needed to define a window and its label:
- metadata.json (window definition: projection, bounds, time_range, options)
- layers/label_100m/ (raster label written at creation time, not from a data source)

All other layers (sentinel1, sentinel2, era5, etc.) and items.json are
regenerated by rslearn dataset prepare/ingest/materialize.
"""

import argparse
import shutil
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

SRC_ROOT = Path(
    "/weka/dfive-default/rslearn-eai/datasets/wildfire/canada_fire_sat_full"
)
DST_ROOT = Path("/weka/dfive-default/rslearn-eai/datasets/wildfire/canada_nbac")

DEFAULT_SPLITS = ["test", "test_hard"]


def copy_window(src_dir: Path, dst_dir: Path) -> bool:
    """Copy metadata.json and label_100m layer from one window directory.

    Returns True if anything was copied, False if skipped (already complete).
    """
    src_meta = src_dir / "metadata.json"
    if not src_meta.exists():
        return False

    dst_dir.mkdir(parents=True, exist_ok=True)

    copied_anything = False

    # metadata.json
    dst_meta = dst_dir / "metadata.json"
    if not dst_meta.exists():
        shutil.copy2(src_meta, dst_meta)
        copied_anything = True

    # label_100m layer (directory tree: completed marker + hash-named subdir)
    src_label = src_dir / "layers" / "label_100m"
    if src_label.exists():
        dst_label = dst_dir / "layers" / "label_100m"
        # Check if a non-empty geotiff.tif already exists (the dataset
        # pipeline can create 0-byte placeholder files).
        label_already_copied = any(
            f.stat().st_size > 0 for f in dst_label.rglob("geotiff.tif")
        )
        if not label_already_copied:
            shutil.copytree(src_label, dst_label, dirs_exist_ok=True)
            copied_anything = True

    return copied_anything


def main() -> None:
    """Copy requested hard-split windows from the source dataset to NBAC."""
    parser = argparse.ArgumentParser(
        description="Copy test/test_hard windows from canada_fire_sat_full to canada_nbac"
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=32,
        help="Number of parallel copy workers (default: 32)",
    )
    parser.add_argument(
        "--splits",
        nargs="+",
        default=DEFAULT_SPLITS,
        help=f"Which splits to copy (default: {DEFAULT_SPLITS})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be copied without copying",
    )
    args = parser.parse_args()

    DST_ROOT.mkdir(parents=True, exist_ok=True)

    tasks: list[tuple[Path, Path]] = []
    for split in args.splits:
        src_split = SRC_ROOT / "windows" / split
        dst_split = DST_ROOT / "windows" / split
        if not src_split.exists():
            print(f"WARNING: source split {src_split} does not exist, skipping")
            continue

        window_names = sorted(d.name for d in src_split.iterdir() if d.is_dir())
        print(f"{split}: {len(window_names)} windows")
        for name in window_names:
            tasks.append((src_split / name, dst_split / name))

    print(f"\nTotal windows to copy: {len(tasks)}")

    if args.dry_run:
        for src, dst in tasks[:5]:
            print(f"  {src} -> {dst}")
        if len(tasks) > 5:
            print(f"  ... and {len(tasks) - 5} more")
        return

    copied = 0
    skipped = 0
    errors = 0

    with ProcessPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(copy_window, src, dst): (src, dst) for src, dst in tasks
        }
        for i, future in enumerate(as_completed(futures), 1):
            try:
                was_copied = future.result()
                if was_copied:
                    copied += 1
                else:
                    skipped += 1
            except Exception as e:
                src, dst = futures[future]
                print(f"ERROR copying {src.name}: {e}")
                errors += 1

            if i % 5000 == 0:
                print(
                    f"  Progress: {i}/{len(tasks)} (copied={copied}, skipped={skipped})"
                )

    print(f"\nDone: {copied} copied, {skipped} skipped, {errors} errors")


if __name__ == "__main__":
    main()
