# Required fields
model_predict_args:
  model_cfg_fname: "data/forest_loss_driver/config_satlaspretrain_flip_oldmodel_unfreeze.yaml" # should be path from the top of the repo IF NOT ABSOLUTE PATH
prepare_args:
  apply_windows_args:
    workers: 112
ingest_args:
  apply_windows_args:
    workers: 112
materialize_args:
  apply_windows_args:
    workers: 112
