version: "3.12"

services:
  # Define the base image
  base-image:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: base-image:latest   # Tag it as "base-image"

  # Define the forest-loss-driver service
  # This is just used for building the Docker image in Github Action.
  # See .github/workflows/forest_loss_driver_prediction.yaml.
  forest-loss-driver:
    build:
      context: .
      dockerfile: Dockerfile
    image: forest_loss_driver:latest
    depends_on:
      - base-image
