# lightning.pytorch==2.4.0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
      log_weight_decay: false
  - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
    init_args:
      module_selector:
      - model
      - encoder
      - 0
      - encoder
      - model
      unfreeze_at_epoch: 5
      unfreeze_lr_factor: 1.0
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: null
      monitor: val_class/accuracy
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: max
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: rslearn.train.prediction_writer.RslearnWriter
    init_args:
      path: gs://rslearn-eai/datasets/forest_loss_driver/prediction/dataset_20241105
      output_layer: output
      path_options: {}
      selector:
      - class
      merger: null
  fast_dev_run: false
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: rslp.forest_loss_driver.train.ForestLossLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
        - class_path: rslearn.models.simple_time_series.SimpleTimeSeries
          init_args:
            encoder:
              class_path: rslearn.models.swin.Swin
              init_args:
                arch: swin_v2_b
                pretrained: true
                input_channels: 3
                output_layers:
                - 1
                - 3
                - 5
                - 7
                num_outputs: 1000
            image_channels: 3
            op: max
            groups:
            - - 0
              - 1
              - 2
            - - 3
              - 4
              - 5
            num_layers: null
        decoders:
          class:
          - class_path: rslearn.models.pooling_decoder.PoolingDecoder
            init_args:
              in_channels: 2048
              out_channels: 10
              num_conv_layers: 1
              num_fc_layers: 2
              conv_channels: 128
              fc_channels: 512
          - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.0001
    plateau: false
    plateau_factor: 0.1
    plateau_patience: 10
    plateau_min_lr: 0.0
    plateau_cooldown: 0
    visualize_dir: null
    restore_config:
      class_path: rslearn.train.lightning_module.RestoreConfig
      init_args:
        restore_path: https://ai2-public-datasets.s3.amazonaws.com/satlas/satlas-model-v1-lowres-multi.pth
        restore_path_options: {}
        selector: []
        ignore_prefixes: []
        remap_prefixes:
        - - backbone.backbone.backbone.
          - encoder.0.encoder.model.
    print_parameters: false
    print_model: false
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    inputs:
      pre_0:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_pre_0
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      pre_1:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_pre_1
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      pre_2:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_pre_2
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      post_0:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_post_0
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      post_1:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_post_1
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      post_2:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: raster
          layers:
          - best_post_2
          bands:
          - R
          - G
          - B
          required: true
          passthrough: true
          is_target: false
          dtype: FLOAT32
      label:
        class_path: rslearn.train.dataset.DataInput
        init_args:
          data_type: vector
          layers:
          - label
          bands: null
          required: true
          passthrough: false
          is_target: true
          dtype: FLOAT32
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslp.forest_loss_driver.train.ForestLossTask
            init_args:
              property_name: new_label
              classes:
              - agriculture
              - mining
              - airstrip
              - road
              - logging
              - burned
              - landslide
              - hurricane
              - river
              - none
              filters: []
              read_class_id: false
              allow_invalid: true
              skip_unknown_categories: false
              prob_property: probs
              metric_kwargs:
                average: micro
              enable_f1_metric: false
              f1_metric_kwargs: {}
              positive_class: null
              positive_class_threshold: 0.5
              image_bands:
              - 0
              - 1
              - 2
              remap_values: null
        input_mapping:
          class:
            label: targets
    path: gs://rslearn-eai/datasets/forest_loss_driver/prediction/dataset_20241105
    path_options: {}
    batch_size: 32
    num_workers: 4
    default_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - peru_interesting
        - peru3
        - peru3_flagged_in_peru
        - nadia2
        - nadia3
        - brazil_interesting
        names: null
        tags: null
        num_samples: null
        transforms:
        - class_path: rslearn.train.transforms.concatenate.Concatenate
          init_args:
            selections:
              pre_0: []
              pre_1: []
              pre_2: []
              post_0: []
              post_1: []
              post_2: []
            output_selector: image
        - class_path: rslearn.train.transforms.normalize.Normalize
          init_args:
            mean: 0.0
            std: 255.0
            valid_range: null
            selectors:
            - image
            bands: null
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 64
            mode: center
            image_selectors:
            - image
            box_selectors: []
        - class_path: rslearn.train.transforms.flip.Flip
          init_args:
            horizontal: true
            vertical: true
            image_selectors:
            - image
            box_selectors: []
        sampler: null
        patch_size: null
        overlap_ratio: null
        load_all_patches: null
        skip_targets: null
    train_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups: null
        names: null
        tags: null
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        overlap_ratio: null
        load_all_patches: null
        skip_targets: null
    val_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups: null
        names: null
        tags: null
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        overlap_ratio: null
        load_all_patches: null
        skip_targets: null
    test_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups: null
        names: null
        tags: null
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        overlap_ratio: null
        load_all_patches: null
        skip_targets: null
    predict_config:
      class_path: rslearn.train.dataset.SplitConfig
      init_args:
        groups:
        - default
        names: null
        tags: null
        num_samples: null
        transforms: null
        sampler: null
        patch_size: null
        overlap_ratio: null
        load_all_patches: null
        skip_targets: true
wandb_run_id: ''
wandb_resume: false
rslp_project: amazon_conservation
rslp_experiment: data_20240912_satlaspretrain_swinb_oldmodel_unfreeze_02
autoresume: false
load_best: true
force_log: false
no_log: false
optimizer: null
lr_scheduler: null
return_predictions: null
ckpt_path: gs://rslearn-eai/projects/amazon_conservation/data_20240912_satlaspretrain_swinb_oldmodel_unfreeze_02/checkpoints/epoch=28-step=2175.ckpt
