data:
  class_path: rslearn.train.data_module.MultiDatasetDataModule
  init_args:
    batch_sizes:
      detect_sentinel2_vessels: 8
    data_modules:
      detect_sentinel2_vessels:
        class_path: rslearn.train.data_module.RslearnDataModule
        init_args:
          batch_size: 8
          default_config:
            transforms:
            - class_path: rslp.transforms.mask.Mask
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel2_l2a
                selections:
                  image: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  sentinel2_l2a:
                  - B02
                  - B03
                  - B04
                  - B08
                  - B05
                  - B06
                  - B07
                  - B8A
                  - B11
                  - B12
                  - B01
                  - B09
                config_fname: /opt/helios/data/norm_configs/computed.json
          inputs:
            image:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2
              passthrough: true
            mask:
              bands:
              - mask
              data_type: raster
              dtype: INT32
              is_target: true
              layers:
              - mask
              passthrough: true
            targets:
              data_type: vector
              is_target: true
              layers:
              - label
          num_workers: 16
          path: /weka/dfive-default/rslearn-eai/datasets/sentinel2_vessels/dataset_v1/20250213/
          task:
            class_path: rslearn.train.tasks.multi_task.MultiTask
            init_args:
              input_mapping:
                detect_sentinel2_vessels:
                  targets: targets
              tasks:
                detect_sentinel2_vessels:
                  class_path: rslearn.train.tasks.detection.DetectionTask
                  init_args:
                    box_size: 15
                    classes:
                    - unknown
                    - vessel
                    enable_f1_metric: true
                    enable_map_metric: true
                    exclude_by_center: true
                    f1_metric_kwargs:
                      cmp_mode: distance
                      cmp_threshold: 15
                      flatten_classes: true
                    f1_metric_thresholds:
                    - - 0.05
                      - 0.1
                      - 0.2
                      - 0.3
                      - 0.4
                      - 0.5
                      - 0.6
                      - 0.7
                      - 0.8
                      - 0.9
                      - 0.95
                    property_name: category
                    remap_values:
                    - - 0
                      - 1
                    - - 0
                      - 255
          test_config:
            groups:
            - sargassum_val
            - split1
            - split7
            patch_size: 128
          train_config:
            groups:
            - sargassum_train
            - split2
            - split3
            - split4
            - split5
            - split6
            - train
            - train-bg
            - train2
            - train3
            patch_size: 128
            sampler:
              class_path: rslearn.train.dataset.RandomSamplerFactory
              init_args:
                num_samples: 131072
                replacement: true
            transforms:
            - class_path: rslp.transforms.mask.Mask
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel2_l2a
                selections:
                  image: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  sentinel2_l2a:
                  - B02
                  - B03
                  - B04
                  - B08
                  - B05
                  - B06
                  - B07
                  - B8A
                  - B11
                  - B12
                  - B01
                  - B09
                config_fname: /opt/helios/data/norm_configs/computed.json
            - class_path: rslearn.train.transforms.flip.Flip
              init_args:
                box_selectors:
                - target/detect_sentinel2_vessels
                image_selectors:
                - image
                - sentinel2_l2a
          val_config:
            groups:
            - sargassum_val
            - split1
            - split7
            patch_size: 128
    num_workers: 16
    refill_batches: true
    sample_mode: random_cycle
model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    lr: 0.0001
    model:
      class_path: rslearn.models.multitask.MultiTaskMergedModel
      init_args:
        decoder_to_target:
          FasterRCNN:
          - detect_sentinel2_vessels
        decoders:
          FasterRCNN:
          - class_path: rslearn.models.faster_rcnn.FasterRCNN
            init_args:
              anchor_sizes:
              - - 32
              downsample_factors:
              - 8
              num_channels: 768
              num_classes: 2
        encoder:
        - class_path: rslp.helios.model.TaskConditionedHelios
          init_args:
            checkpoint_path: /weka/dfive-default/helios/checkpoints/favyen/v0.2_base_latent_mim_128_alldata_random_fixed_modality_0.5/step320000
            forward_kwargs:
              patch_size: 8
            model_overrides:
              encoder_config:
                task_lora_kwargs:
                  gen_hidden: 64
                  no_task_conditioning: true
                  task_lora_indices:
                  - 0
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  - 6
                  - 7
                  - 8
                  - 9
                  - 10
                  - 11
                  use_task_lora: true
            selector:
            - encoder
            task_embed_opts:
              path: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/data/task_embeds___Qwen3-Embedding-8B__256d__anchor__instruct__from_yaml.pt
              type: precomputed
        lazy_decode: true
        task_label_offsets:
          detect_sentinel2_vessels:
            num_outputs: 2
            offset: 0
            outputs_key: labels
    scheduler:
      class_path: rslearn.train.scheduler.CosineAnnealingScheduler
      init_args:
        T_max: 100
        eta_min: 0
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        input_mapping:
          detect_sentinel2_vessels:
            targets: targets
        tasks:
          detect_sentinel2_vessels:
            class_path: rslearn.train.tasks.detection.DetectionTask
            init_args:
              box_size: 15
              classes:
              - unknown
              - vessel
              enable_f1_metric: true
              enable_map_metric: true
              exclude_by_center: true
              f1_metric_kwargs:
                cmp_mode: distance
                cmp_threshold: 15
                flatten_classes: true
              f1_metric_thresholds:
              - - 0.05
                - 0.1
                - 0.2
                - 0.3
                - 0.4
                - 0.5
                - 0.6
                - 0.7
                - 0.8
                - 0.9
                - 0.95
              property_name: category
              remap_values:
              - - 0
                - 1
              - - 0
                - 255
rslp_experiment: placeholder
rslp_project: placeholder
trainer:
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      every_n_epochs: 10
      mode: min
      monitor: val_loss
      save_last: true
      save_top_k: 1
  - class_path: rslearn.train.callbacks.freeze_unfreeze.MultiStageFineTuning
    init_args:
      stages:
      - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
        init_args:
          at_epoch: 0
          freeze_selectors:
          - encoder
          unfreeze_selectors:
          - head
      - class_path: rslearn.train.callbacks.freeze_unfreeze.FTStage
        init_args:
          at_epoch: 20
          freeze_selectors:
          - encoder
          unfreeze_lr_factor: 10
          unfreeze_selectors:
          - head
          - lora
  max_epochs: 100
