base_cfg: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v3_multitask/base.yaml
output_path: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v3_singletask/OUT_classify.yaml

dataset_cfgs:
  - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_landsat_vessels/finetune_classifier_cosinelr.yaml
  - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_nandi_crop_type/finetune_s1_s2_cosinelr.yaml
  - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_worldcereal_cropland/finetune_s1_s2_cosinelr.yaml

global_overrides:
  trainer:
    accumulate_grad_batches: 3
  model:
    init_args:
      model:
        init_args:
          task_embedding:
            class_path: rslearn.models.task_embedding.TaskMHAEmbedding
            init_args:
              encoder_embedding_size: 768
              num_heads: 12

merge_options:
  merge_heads: true
  merge_task_labels: true
  same_label_groups:

substitutions:
  patch_size: 8
  encoder_embedding_size: 768
  helios_checkpoint_path: /weka/dfive-default/helios/checkpoints/favyen/v0.2_base_latent_mim_128_alldata_random_fixed_modality_0.5/step320000
