trainer:
  callbacks+:
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0]
        unfreeze_at_epoch: 5
        unfreeze_lr_factor: 5

model:
  init_args:
    lr: 0.00005