base_cfg: /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/2025_07_31_moe/base.yaml

dataset_cfgs:
  - - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_pastis/basecfg_cosinelr.yaml
    - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_pastis/basecfg_helios_mm.yaml
  - - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_satlas_solar_farm_128/basecfg_cosinelr.yaml
    - /weka/dfive-default/ryanp/rslearn_projects/one_off_projects/2025_07_joint_finetune/configs/v2_satlas_solar_farm_128/basecfg_helios_mm.yaml
 
substitutions:
  patch_size: 8
  encoder_embedding_size: 768
  helios_checkpoint_path: /weka/dfive-default/helios/checkpoints/favyen/v0.2_base_latent_mim_128_alldata_random_fixed_modality_0.5/step320000

global_overrides:
  model:
    init_args:
      model:
        init_args:
          trunk:
            class_path: rslearn.models.trunk.DecoderTrunk
            init_args:
              task_embedding:
                class_path: rslearn.models.task_embedding.TaskChannelEmbedding
                init_args:
                  encoder_embedding_size: 768
                  add_spatial_embed: true
              layers:
              - class_path: rslearn.models.trunk.MoETransformer
                init_args:
                  dim: 768
                  n_layers: 1
                  n_heads: 12
                  num_experts: 4
                  num_slots: 4

local_overrides:
  val_config:
    load_all_patches: false

merge_options:
  merge_heads: true
  merge_task_labels: true
  same_label_groups:
