# FIXME ${TRAINER_DATA_PATH}
# FIXME ${WANDB_PROJECT}: wandb project for the trainer to log metrics to
# FIXME ${WANDB_NAME}: wandb name for the trainer to log metrics to
# FIXME ${WANDB_ENTITY}: wandb entity for the trainer to log metrics to
model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslp.helios.model.Helios
            init_args:
              # this EXTRA_FILES_PATH needs to be manually copied into the
              # GCS bucket. It is the helios checkpoint which was finetuned
              # to obtain the checkpoint being referenced in ES Run.
              checkpoint_path: ${EXTRA_FILES_PATH}helios/step300000
              random_initialization: true
              selector: ["encoder"]
              forward_kwargs:
                patch_size: 1
        decoders:
          crop_type_classification:
            - class_path: rslp.crop.kenya_nandi.train.SegmentationPoolingDecoder
              init_args:
                in_channels: 768
                out_channels: 7
            - class_path: rslearn.train.tasks.segmentation.SegmentationHead
    lr: 0.0001
    plateau: true
    plateau_factor: 0.2
    plateau_patience: 2
    plateau_min_lr: 0
    plateau_cooldown: 10
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: ${DATASET_PATH}
    inputs:
      sentinel2_l2a:
        data_type: "raster"
        layers: ["sentinel2"]
        bands: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
        passthrough: true
        dtype: FLOAT32
        load_all_item_groups: true
        load_all_layers: true
      sentinel1:
        data_type: "raster"
        layers: ["sentinel1_descending"]
        bands: ["vv", "vh"]
        passthrough: true
        dtype: FLOAT32
        load_all_item_groups: true
        load_all_layers: true
      label:
        data_type: "raster"
        layers: ["label_raster"]
        bands: ["label"]
        is_target: true
        dtype: INT32
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          crop_type_classification:
            class_path: rslearn.train.tasks.segmentation.SegmentationTask
            init_args:
              num_classes: 7
              zero_is_invalid: false
              metric_kwargs:
                average: "micro"
              other_metrics:
                water_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 0
                water_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 0
                bareground_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 1
                bareground_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 1
                rangeland_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 2
                rangeland_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 2
                floodedvegetation_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 3
                floodedvegetation_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 3
                trees_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 4
                trees_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 4
                cropland_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 5
                cropland_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 5
                buildings_precision:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassPrecision
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 6
                buildings_recall:
                  class_path: rslearn.train.tasks.segmentation.SegmentationMetric
                  init_args:
                    metric:
                      class_path: torchmetrics.classification.MulticlassRecall
                      init_args:
                        num_classes: 7
                        average: null
                    class_idx: 6
        input_mapping:
          crop_type_classification:
            label: "targets"
    batch_size: 32
    num_workers: ${NUM_WORKERS}
    default_config:
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 4
            mode: "center"
            image_selectors: ["sentinel2_l2a", "target/crop_type_classification/classes", "target/crop_type_classification/valid"]
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
    train_config:
      groups: ["gaza"]
      tags:
        split: "train"
    val_config:
      groups: ["gaza"]
      tags:
        split: "test"
    test_config:
      groups: ["gaza"]
      tags:
        split: "test"
    predict_config:
      groups: ["gaza"]
      load_all_patches: true
      skip_targets: true
      overlap_ratio: 0.75
      patch_size: 4
      transforms:
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            size: 4
            mode: "center"
            image_selectors: ["sentinel2_l2a"]
        - class_path: rslp.helios.norm.HeliosNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
trainer:
  max_epochs: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_loss
        mode: min
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0]
        unfreeze_at_epoch: 2
    - class_path: rslearn.train.prediction_writer.RslearnWriter
      init_args:
        path: ${DATASET_PATH}
        output_layer: ${PREDICTION_OUTPUT_LAYER}
        selector: ["crop_type_classification"]
        merger:
          class_path: rslearn.train.prediction_writer.RasterMerger
          init_args:
            padding: 2
