data:
  class_path: rslearn.train.data_module.MultiDatasetDataModule
  init_args:
    batch_sizes:
      cropland_classification: 16
      vessel_detection: 8
    data_modules:
      cropland_classification:
        class_path: rslearn.train.data_module.RslearnDataModule
        init_args:
          batch_size: 16
          default_config:
            transforms:
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel2_l2a
                selections:
                  sentinel2_0: []
                  sentinel2_1: []
                  sentinel2_10: []
                  sentinel2_11: []
                  sentinel2_2: []
                  sentinel2_3: []
                  sentinel2_4: []
                  sentinel2_5: []
                  sentinel2_6: []
                  sentinel2_7: []
                  sentinel2_8: []
                  sentinel2_9: []
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: sentinel1
                selections:
                  sentinel1_0: []
                  sentinel1_1: []
                  sentinel1_10: []
                  sentinel1_11: []
                  sentinel1_2: []
                  sentinel1_3: []
                  sentinel1_4: []
                  sentinel1_5: []
                  sentinel1_6: []
                  sentinel1_7: []
                  sentinel1_8: []
                  sentinel1_9: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  sentinel1:
                  - vv
                  - vh
                  sentinel2_l2a:
                  - B02
                  - B03
                  - B04
                  - B08
                  - B05
                  - B06
                  - B07
                  - B8A
                  - B11
                  - B12
                  - B01
                  - B09
                config_fname: /opt/helios/data/norm_configs/computed.json
            - class_path: rslearn.train.transforms.pad.Pad
              init_args:
                image_selectors:
                - sentinel2_l2a
                - sentinel1
                mode: center
                size: 8
          inputs:
            label:
              data_type: vector
              is_target: true
              layers:
              - label
            sentinel1_0:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1
              passthrough: true
            sentinel1_1:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.1
              passthrough: true
            sentinel1_10:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.10
              passthrough: true
            sentinel1_11:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.11
              passthrough: true
            sentinel1_2:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.2
              passthrough: true
            sentinel1_3:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.3
              passthrough: true
            sentinel1_4:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.4
              passthrough: true
            sentinel1_5:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.5
              passthrough: true
            sentinel1_6:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.6
              passthrough: true
            sentinel1_7:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.7
              passthrough: true
            sentinel1_8:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.8
              passthrough: true
            sentinel1_9:
              bands:
              - vv
              - vh
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel1.9
              passthrough: true
            sentinel2_0:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2
              passthrough: true
            sentinel2_1:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.1
              passthrough: true
            sentinel2_10:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.10
              passthrough: true
            sentinel2_11:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.11
              passthrough: true
            sentinel2_2:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.2
              passthrough: true
            sentinel2_3:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.3
              passthrough: true
            sentinel2_4:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.4
              passthrough: true
            sentinel2_5:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.5
              passthrough: true
            sentinel2_6:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.6
              passthrough: true
            sentinel2_7:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.7
              passthrough: true
            sentinel2_8:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.8
              passthrough: true
            sentinel2_9:
              bands:
              - B02
              - B03
              - B04
              - B08
              - B05
              - B06
              - B07
              - B8A
              - B11
              - B12
              - B01
              - B09
              data_type: raster
              dtype: FLOAT32
              layers:
              - sentinel2.9
              passthrough: true
          num_workers: 32
          path: /weka/dfive-default/rslearn-eai/datasets/crop/worldcereal_cropland/20250626
          task:
            class_path: rslearn.train.tasks.multi_task.MultiTask
            init_args:
              input_mapping:
                cropland_classification:
                  label: targets
              tasks:
                cropland_classification:
                  class_path: rslearn.train.tasks.classification.ClassificationTask
                  init_args:
                    classes:
                    - Cropland
                    - Non-Cropland
                    enable_f1_metric: true
                    metric_kwargs:
                      average: micro
                    property_name: category
          test_config:
            groups:
            - h3_sample100_66K
            tags:
              split: val
          train_config:
            groups:
            - h3_sample100_66K
            tags:
              split: train
          val_config:
            groups:
            - h3_sample100_66K
            tags:
              split: val
      vessel_detection:
        class_path: rslearn.train.data_module.RslearnDataModule
        init_args:
          batch_size: 8
          default_config:
            transforms:
            - class_path: rslp.transforms.mask.Mask
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: landsat
                selections:
                  image: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  landsat:
                  - B8
                  - B1
                  - B2
                  - B3
                  - B4
                  - B5
                  - B6
                  - B7
                  - B9
                  - B10
                  - B11
                config_fname: /opt/helios/data/norm_configs/computed.json
          inputs:
            image:
              bands:
              - B8
              - B1
              - B2
              - B3
              - B4
              - B5
              - B6
              - B7
              - B9
              - B10
              - B11
              data_type: raster
              dtype: FLOAT32
              layers:
              - landsat
              passthrough: true
            mask:
              bands:
              - mask
              data_type: raster
              dtype: INT32
              is_target: true
              layers:
              - mask
              passthrough: true
            targets:
              data_type: vector
              is_target: true
              layers:
              - label
          num_workers: 16
          path: /weka/dfive-default/rslearn-eai/datasets/landsat_vessel_detection/detector/dataset_20250624
          task:
            class_path: rslearn.train.tasks.multi_task.MultiTask
            init_args:
              input_mapping:
                vessel_detection:
                  targets: targets
              tasks:
                vessel_detection:
                  class_path: rslearn.train.tasks.detection.DetectionTask
                  init_args:
                    box_size: 15
                    classes:
                    - unknown
                    - vessel
                    enable_f1_metric: true
                    enable_map_metric: true
                    exclude_by_center: true
                    f1_metric_kwargs:
                      cmp_mode: distance
                      cmp_threshold: 15
                      flatten_classes: true
                    f1_metric_thresholds:
                    - - 0.05
                      - 0.1
                      - 0.2
                      - 0.3
                      - 0.4
                      - 0.5
                      - 0.6
                      - 0.7
                      - 0.8
                      - 0.9
                      - 0.95
                    property_name: category
                    remap_values:
                    - - 0
                      - 1
                    - - 0
                      - 255
                    score_threshold: 0.7
          test_config:
            groups:
            - labels_utm
            load_all_patches: true
            patch_size: 128
            tags:
              split: val
          train_config:
            groups:
            - labels_utm
            load_all_patches: true
            patch_size: 128
            tags:
              split: train
            transforms:
            - class_path: rslp.transforms.mask.Mask
            - class_path: rslearn.train.transforms.concatenate.Concatenate
              init_args:
                output_selector: landsat
                selections:
                  image: []
            - class_path: rslp.helios.norm.HeliosNormalize
              init_args:
                band_names:
                  landsat:
                  - B8
                  - B1
                  - B2
                  - B3
                  - B4
                  - B5
                  - B6
                  - B7
                  - B9
                  - B10
                  - B11
                config_fname: /opt/helios/data/norm_configs/computed.json
          val_config:
            groups:
            - labels_utm
            load_all_patches: true
            patch_size: 128
            tags:
              split: val
    num_workers: 16
    refill_batches: false
    sample_mode: random_cycle
model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    lr: 0.0001
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        decoders:
          cropland_classification:
          - class_path: rslearn.models.pooling_decoder.PoolingDecoder
            init_args:
              in_channels: 768
              out_channels: 2
          - class_path: rslearn.train.tasks.classification.ClassificationHead
          vessel_detection:
          - class_path: rslearn.models.faster_rcnn.FasterRCNN
            init_args:
              anchor_sizes:
              - - 32
              downsample_factors:
              - 8
              num_channels: 768
              num_classes: 2
        encoder:
        - class_path: rslp.helios.model.Helios
          init_args:
            checkpoint_path: /weka/dfive-default/helios/checkpoints/favyen/v0.2_base_latent_mim_128_alldata_random_fixed_modality_0.5/step320000
            forward_kwargs:
              patch_size: 8
            selector:
            - encoder
        lazy_decode: true
    scheduler:
      class_path: rslearn.train.scheduler.CosineAnnealingScheduler
      init_args:
        T_max: 30
        eta_min: 0
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        input_mapping:
          cropland_classification:
            label: targets
          vessel_detection:
            targets: targets
        tasks:
          cropland_classification:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              classes:
              - Cropland
              - Non-Cropland
              enable_f1_metric: true
              metric_kwargs:
                average: micro
              property_name: category
          vessel_detection:
            class_path: rslearn.train.tasks.detection.DetectionTask
            init_args:
              box_size: 15
              classes:
              - unknown
              - vessel
              enable_f1_metric: true
              enable_map_metric: true
              exclude_by_center: true
              f1_metric_kwargs:
                cmp_mode: distance
                cmp_threshold: 15
                flatten_classes: true
              f1_metric_thresholds:
              - - 0.05
                - 0.1
                - 0.2
                - 0.3
                - 0.4
                - 0.5
                - 0.6
                - 0.7
                - 0.8
                - 0.9
                - 0.95
              property_name: category
              remap_values:
              - - 0
                - 1
              - - 0
                - 255
              score_threshold: 0.7
rslp_experiment: placeholder
rslp_project: placeholder
trainer:
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      mode: min
      monitor: val_loss
      save_last: true
      save_top_k: 1
  max_epochs: 100
