model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    restore_config:
      restore_path: /weka/dfive-default/ryanp/rslearn_projects/project_data/projects/helios_finetune_cosine_lr/soup/checkpoints/last.ckpt
      selector:
        - state_dict
      ignore_prefixes:
        - model.decoders.
      remap_prefixes:
        - - model.encoder
          - encoder
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        decoders:
          segment:
            - class_path: rslearn.models.unet.UNetDecoder
              init_args:
                in_channels: [[4, 128], [8, 256], [16, 512], [32, 1024]]
                out_channels: 20
                conv_layers_per_resolution: 2
            - class_path: rslearn.train.tasks.segmentation.SegmentationHead
    lr: 0.0001
    scheduler:
      class_path: rslearn.train.scheduler.CosineAnnealingScheduler
      init_args:
        T_max: 150
        eta_min: 0
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: /weka/dfive-default/rslearn-eai/datasets/pastis/rslearn_dataset/
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          segment:
            class_path: rslearn.train.tasks.segmentation.SegmentationTask
            init_args:
              num_classes: 20
              remap_values: [[0, 1], [0, 255]]
              zero_is_invalid: true
              metric_kwargs:
                average: "micro"
              enable_miou_metric: true
        input_mapping:
          segment:
            targets: "targets"
    batch_size: 8
    num_workers: 16
    train_config:
      groups: ["fold1", "fold2", "fold3"]
    val_config:
      groups: ["fold4"]
    test_config:
      groups: ["fold5"]
trainer:
  max_epochs: 500
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_segment/accuracy
        mode: max
rslp_project: placeholder
rslp_experiment: placeholder
