name: Landsat-Vessel-Detection

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "landsat_vessels_v*" # Trigger only when a version tag (e.g., landsat_vessels_v0.0.1) is pushed

jobs:
  build-and-push:
    uses: ./.github/workflows/publish_project_docker_image.yaml
    with:
      rslp_project: "landsat_vessels"
      image_name: "landsat-vessel-detection"
