name: Sentinel2-Vessel-Detection

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "sentinel2_vessels_v*" # Trigger only when a version tag (e.g., sentinel2_vessels_v0.0.1) is pushed

jobs:
  build-and-push:
    uses: ./.github/workflows/publish_project_docker_image.yaml
    with:
      rslp_project: "sentinel2_vessels"
      image_name: "sentinel2-vessel-detection"
